AnimalPicture = {
    'Janwaron ki aankhe andhere me 6 guna zyada roshni dekhti hain.': True,
    'Kuch birds bina ruke kai hafton tak hawa me so sakte hain.': True,
    'Octopus ke paas 3 dil aur neela khoon hota hai.': True,
    'Sher ki dahad 8 km door tak sunai deti hai.': True,
    'Bhalu thand me mahino tak hibernation me sote hain.': True,
    'Cheetah ki speed 100 km/h tak pahunch sakti hai.': True,
    'Giraffe ki jeebh 20 inch lambi aur neele rang ki hoti hai.': False,
    'Dolphin ek aankh khol kar soti hai.': False,
    'Kangaroo ulta nahi chal sakte hain.': False,
    'Elephant jump nahi kar sakte hain.': False,
    'Butterfly apne pairo se swad leti hai.': False,
    'Shark ki haddiyan nahi hoti, poora skeleton cartilage ka hota hai.': False,
    'Koali apni zindagi ka 90% sote hue bitate hain.': False,
    'Tiger ki skin par bhi dhariyan hoti hain agar baal hata diye jayein.': False,
    'Penguin khara pani pee sakte hain kyunki unke paas salt gland hota hai.': False,
    'Owl 360 degree tak apna sir guma sakte hain.': False,
    'Bees ki 5 aankhe hoti hain.': False,
    'Horse khade-khade so sakte hain.': False,
    'Flamingo pink isliye hote hain kyunki wo shrimp khate hain.': False,
    'Snail 3 saal tak so sakta hai.': False,
    'Crocodile apni jeebh bahar nahi nikal sakte.': False,
    'Starfish ke paas dimaag nahi hota.': False,
    'Housefly ki life span sirf 2 weeks hoti hai.': False,
    'Jellyfish 95% paani se bani hoti hai.': False,
    'Camel ke paas 3 eyelids hoti hain jo unhe ret se bachati hain.': False,
    'Squirrels plant lagane me anjaane me madad karti hain kyunki wo nuts bhool jaati hain.': False,
    'Bat ekmatra mammal hai jo ud sakta hai.': False,
    'Platypus ke paas pet nahi hota hai.': False,
    'Otter sote waqt ek dusre ka haath pakad kar sote hain taaki beh na jayein.': False,
    'Panda din me 12 ghante bamboo khane me lagata hai.': False,
    'Hedgehog paani me tair sakte hain.': False,
    'Chameleon ki jeebh uski body se lambi hoti hai.': False,
    'Zebra ki dhariyan har ek me alag hoti hain jaise human fingerprints.': False,
    'Owl ki aakhon ki putliyan move nahi karti, wo sir ghumate hain.': False,
    'Ants apne wajan se 50 guna zyada wajan utha sakti hain.': False,
    'Blue whale ki tongue ka wajan ek elephant jitna hota hai.': False,
    'Wolf pack ka ek strict social hierarchy system hota hai.': False,
    'Eagle 3 km door se apne shikaar ko dekh sakta hai.': False,
    'Cat ki aawaz me 100 se zyada alag tarah ke tones hote hain.': False,
    'Dog ki smell power human se 10,000 guna zyada hoti hai.': False,
    'Squirrel ki teeth kabhi badhna band nahi karte.': False,
    'Goat ki rectangular pupils hoti hain jisse wide vision milta hai.': False,
    'Hippopotamus paani ke andar bhi saans rok kar so sakta hai.': False,
    'Rabbit bina apna sir gumaaye piche ka bhi dekh sakta hai.': False,
    'Leopard ped par badi aasani se chad sakta hai.': False,
    'Vulture ki digestion power itni strong hoti hai ki wo bacteria destroy kar dete hain.': False,
    'Turkey bird ke paas flight muscles weak hoti hain.': False,
    'Seahorse me male bacho ko जन्म deta hai.': False,
    'Armadillo bulletproof shell ke liye jana jata hai.': False,
    'Caterpillar ke paas 4000 se zyada muscles hoti hain.': False
}

# 2. War (50 items)
War = {
    'History ki sabse lambi jang sirf 38 minute chali thi.': True,
    'World War me pigeons ne secret messages deliver kiye the.': True,
    'Purane zamane me war ke liye haathiyo ka use hota hai.': True,
    'Enigma machine ne World War 2 ka rukh badal diya tha.': False,
    'Purane kile aisi engineering se bante the jo todna namumkin tha.': False,
    'Spartan warriors bachpan se hi military training shuru kar dete the.': False,
    'Roman empire ke paas world ki sabse disciplined army thi.': False,
    'Trojan war me wooden horse ka use kiya gaya tha.': False,
    'Samurai warriors Japan me honor ke liye jeete the.': False,
    'World War 1 me tank sabse pehle use kiye gaye the.': False,
    'Cold War me direct fighting nahi hui balki arms race thi.': False,
    'Guerrilla warfare tactics me chhupkar hamla kiya jata hai.': False,
    'Naval wars me submarines game changer sabit hui hain.': False,
    'Cyber warfare aaj ke samay me sabse bada threat ban gaya hai.': False,
    'Drones ka use modern wars me tezi se badh gaya hai.': False,
    'Geneva Convention war prisoners ke rights protect karta hai.': False,
    'Nuclear weapons ki shakti poori duniya ko tabah kar sakti hai.': False,
    'Kamikaze pilots WWII me apne planes dushman par crash kar dete the.': False,
    'Radar technology WWII ke dauran invent ki gayi thi.': False,
    'Sun Tzu ki book The Art of War military strategy ke liye famous hai.': False,
    'Mongol empire ne horse archers ki madad se bada area jeeta tha.': False,
    'Crusades medieval period ki religious wars thin.': False,
    'Battle of Waterloo Napoleon ki final defeat thi.': False,
    'Vietnam war me helicopter ka massive use hua tha.': False,
    ' trench warfare WWII me soldiers ke liye nightmare thi.': False,
    'Military intelligence war jeetne me sabse bada role play karti hai.': False,
    'Cavalry units purane zamane me fast attack ke liye thi.': False,
    'Siege engines se bade kile ki deewarein todi jaati thin.': False,
    'Chemical weapons ka use ab international law ke tahat ban hai.': False,
    'Red Cross ki shuruwat war wounded soldiers ki help ke liye hui thi.': False,
    'Ak-47 rifle history ki sabse widely used gun hai.': False,
    'Aircraft carriers samundar me chalte-firte air base hote hain.': False,
    'Stealth aircraft radar ki pakad me nahi aate hain.': False,
    'Military satellites global positioning aur communication ke liye hoti hain.': False,
    'Medal of Honor bravery ke liye diya jane wala top award hai.': False,
    'Pyrrhic victory aisi jeet hoti hai jisme nuksan bahut zyada hota hai.': False,
    'Treaty of Versailles ne WWI ko khatam kiya tha.': False,
    'Blitzkrieg tactic fast German military attack ke liye thi.': False,
    'Code talkers WWII me unbreakable languages use karte the.': False,
    'Fortifications cities ko secure rakhne ke liye banayi jaati thin.': False,
    'Mercenaries paise ke liye ladne wale soldiers hote hain.': False,
    'Ballistic missiles intercontinental targets ko hit kar sakti hain.': False,
    'Sonar technology samundar ke andar submarines detect karti hai.': False,
    'Bulletproof vests soldiers ki jaan bachati hain.': False,
    'Night vision goggles andhere me dekhne me help karte hain.': False,
    'Military logistics poori army ko supply chain maintain rakhti hai.': False,
    'Propaganda war ke dauran public opinion badalne ke liye hota hai.': False,
    'Peacekeeping forces UN ke dwara deploy ki jaati hain.': False,
    'War memorials un soldiers ki yaad me hote hain jo shahid hue.': False,
    'Artificial Intelligence ab military defense me use ho rahi hai.': False
}

# 3. IndiaPak (50 items)
IndiaPak = {
    'Wagah Border ki Beating Retreat ceremony iconic hai.': True,
    'India-Pak border line ko Radcliffe Line kehte hain.': True,
    'Siachen Glacier duniya ka sabse uncha militarized zone hai.': True,
    '1971 war ke baad Shimla Agreement sign hua tha.': False,
    'Dono desho ki cultural roots aapas me judi hain.': False,
    '1947 me partition ke baad dono nations independent hue the.': False,
    'Indus Waters Treaty rivers ke paani ko divide karti hai.': False,
    'Lahore Bus Yatra peace initiative ka ek hissa thi.': False,
    'Cricket matches dono countries me high voltage emotions laate hain.': False,
    'Kartarpur Corridor pilgrims ke liye bina visa visit allow karta hai.': False,
    '1965 ki war kutch aur kashmir border par ladhi gayi thi.': False,
    'Kargil conflict 1999 me high altitude par hua tha.': False,
    'LOC (Line of Control)ashmir region ko divide karti hai.': False,
    'Sufi music aur qawwali dono desho me common heritage hain.': False,
    'Bollywood movies aur music dono taraf pasand kiye jaate hain.': False,
    'Tashkent Declaration 1966 me sign hua tha.': False,
    'Samjhauta Express train service dono desho ke beech chalti thi.': False,
    'Shalimar Bagh Mughal architecture ka symbol hai.': False,
    'Biryani aur Chai dono cultures ka favourite part hai.': False,
    'Ghulam Ali aur Nusrat Fateh Ali Khan ke fans dono taraf hain.': False,
    'Cross-border trade ke liye kuch checkposts banaye gaye hain.': False,
    '1983 aur 2011 World Cups me cricket rivalry dekhne ko mili.': False,
    'Gujral Doctrine India ki neighbourhood policy ka part raha hai.': False,
    'Maritime boundary Sir Creek area me dispute ka mudda hai.': False,
    'Cultural exchange programs history me promote kiye gaye hain.': False,
    'Classical dance aur music forms me similarities hain.': False,
    'Urdu language ki roots dono desho me strong hain.': False,
    'Partition ki stories oral history archives me save hain.': False,
    'Diplomatic missions dono capitals me established hain.': False,
    'UN observers border area me peace monitor karte rahe hain.': False,
    'Himalayan ecosystem dono desho me shared hai.': False,
    'Monsoon pattern dono regions ki agriculture ko affect karta hai.': False,
    'Traditional textiles aur crafts me common designs hain.': False,
    'Railway history pre-independence era se shared hai.': False,
    'Postal services history me connect karti thin.': False,
    'Archaeological sites jaise Harappa Pakistan me hain.': False,
    'Taxila ancient university region ka important center tha.': False,
    'Sikh shrines jaise Nankana Sahib Pakistan me sthit hain.': False,
    'Kashmir issue UN security council resolutions me discuss hua hai.': False,
    'Aman Ki Asha initiative media houses ne start kiya tha.': False,
    'Nobel Peace Prize winners me shared values ki baatein hui hain.': False,
    'Diaspora communities abroad me aapas me milti hain.': False,
    'Military hotlines emergency communication ke liye hoti hain.': False,
    'SAARC summit regional cooperation ke liye platform raha hai.': False,
    'Traditional food items jaise Samosa aur Jalebi common hain.': False,
    'Folk tales aur poetry me Heer-Ranjha ki kahani famous hai.': False,
    'Dono desho me youth population ka bada percentage hai.': False,
    'Environmental issues jaise smog shared problem hain.': False,
    'Space cooperation par bhi past me discussions hue hain.': False,
    'Geopolitical importance South Asia region me critical hai.': False
}

# 4. NaturalDisaster (50 items)
NaturalDisaster = {
    'Ring of Fire me duniya ke 75% active volcanoes hain.': True,
    'Tsunami waves samundar ke andar bhookamp se banti hain.': False,
    'Duniya ka sabse bada volcano Mauna Loa hai.': False,
    'Jungle ki aag garmi aur sadi patti se lagati hai.': False,
    'Richter scale par earthquake ki intensity measure hoti hai.': False,
    'Hurricanes aur typhoons tropical oceans me bante hain.': False,
    'Tornadoes ki wind speed 400 km/h tak ho sakti hai.': False,
    'Avalanche snow slopes par achanak slide hone se hota hai.': False,
    'Drought lambe samay tak barish na hone ki wajah se hota hai.': False,
    'Landslide heavy rain ya earthquake se hill slopes par hota hai.': False,
    'Volcanic ash aviation engine ke liye dangerous hoti hai.': False,
    'Earthquake ke waves ko seismograph se record karte hain.': False,
    'Flood rivers overflow hone ya cloudburst se aati hai.': False,
    'Wildfires ko control karna bahut difficult hota hai.': False,
    'Lightning strike se kai baar bade forest fires shuru hote hain.': False,
    'Sinkholes zameen ke andar cave collapse hone se bante hain.': False,
    'Blizzard severe snowstorm ko kehte hain jisme visibility low hoti hai.': False,
    'Heatwave extreme temperature increase hone se hoti hai.': False,
    'Cyclone ka eye center calm area hota hai.': False,
    'Seismic waves primary aur secondary waves me divide hoti hain.': False,
    'Pacific Tsunami Warning Center earthquakes detect karta hai.': False,
    'Magma zameen ke andar hota hai aur lava bahar aane par kehte hain.': False,
    'Supervolcanoes huge explosive eruptions kar sakte hain.': False,
    'Monsoon floods south asia me har saal common hain.': False,
    'El Nino weather pattern global climate ko affect karta hai.': False,
    'La Nina conditions opposite effects laati hain.': False,
    'Glacier melting se sea level rise ho raha hai.': False,
    'Tidal waves moon gravity aur storms ki wajah se hoti hain.': False,
    'Dust storms desert regions me visibility zero kar dete hain.': False,
    'Hailstorms me barish ke sath bade ice pieces girte hain.': False,
    'Limnic eruption lake ke andar se gas release hone se hota hai.': False,
    'Pyroclastic flow volcano se nikli hot gas aur ash hoti hai.': False,
    'Epicenter earthquake ka surface point hota hai.': False,
    'Fault lines tectonic plates ke boundaries hoti hain.': False,
    'Emergency kits natural disaster ke time life save karti hain.': False,
    'Meteorological departments weather forecasting karte hain.': False,
    'Red cross disaster relief operations me lead karti hai.': False,
    'Building codes earthquake-resistant structures ke liye hote hain.': False,
    'Evacuation plans disaster management ka important part hain.': False,
    'Climate change extreme weather events ko badha raha hai.': False,
    'Saffir-Simpson scale hurricanes ki category measure karti hai.': False,
    'Fujita scale tornadoes ki strength measure karti hai.': False,
    'Volcanic explosivity index eruptions rank karta hai.': False,
    'Aftershocks main earthquake ke baad aate hain.': False,
    'Tsunami ki speed jet plane jitni fast ho sakti hai.': False,
    'Acid rain volcanic gases aur pollution se hoti hai.': False,
    'Permafrost thaw hone se methane gas release hoti hai.': False,
    'Wildfire smoke hazaron miles door tak travel kar sakti hai.': False,
    'Natural disasters economies ko bada nuksan dete hain.': False,
    'Early warning systems hazaron logo ki jaan bachate hain.': False
}

# 5. SeaCreature (50 items)
SeaCreature = {
    'Blue Whale ka dil ek choti car ke size ka hota hai.': True,
    'Deep sea ki machliyan bioluminescence paida karti hain.': True,
    'Shark ki skin par teeth jaisi scales hoti hain.': False,
    'Coral reefs ko samundar ka rain forest kehte hain.': False,
    'Jellyfish bina dimaag ke rehne wale jeev hain.': False,
    'Octopus ke paas 3 hearts aur 9 brains hote hain.': False,
    'Electric eel 600 volts tak ka shock de sakti hai.': False,
    'Seahorse male eggs carry karta hai aur birth deta hai.': False,
    'Manta ray ki wing span bahut badi hoti hai.': False,
    'Clownfish anemone ke sath symbiotic relationship me rehti hai.': False,
    'Squid ki aakhon ka size basketball jitna ho sakta hai.': False,
    'Sea turtle hazaron miles travel karke wapas nesting beach aate hain.': False,
    'Crab side ways move karte hain.': False,
    'Starfish apna lost arm dobara grow kar sakti hai.': False,
    'Killer whales sebenarnya dolphins ki family se belong karti hain.': False,
    'Anglerfish ke paas glowing lure hota hai shikaar ke liye.': False,
    'Pufferfish danger me aane par phool jaati hai aur poison release karti hai.': False,
    'Stingray ke tail par venomous barb hoti hai.': False,
    'Walrus ke paas long tusks hote hain ice todne ke liye.': False,
    'Seal aur sea lion me main difference ear flaps ka hota hai.': False,
    'Manatee ko sea cow bhi kaha jata hai.': False,
    'Lobster ka blood colorless hota hai jo oxygen milne par blue hota hai.': False,
    'Oyster pearls produce karte hain jab koi irritant andar jata hai.': False,
    'Barnacles rock par chipke rehte hain aur filter feeding karte hain.': False,
    'Sea urchin ke paas sharp spines hote hain protection ke liye.': False,
    'Moray eel cave me chhipkar shikaar ka wait karti hai.': False,
    'Barracuda apni tezi aur sharp teeth ke liye jaani jaati hai.': False,
    'Swordfish ki nose sword jaisi long hoti hai.': False,
    'Hammerhead shark ki head shape 360 vision deti hai.': False,
    'Great white shark top ocean predator hai.': False,
    'Nautilus ancient shelled cephalopod hai.': False,
    'Sea sponge ke paas tissues ya organs nahi hote.': False,
    'Plankton ocean food web ka foundation hai.': False,
    'Krill blue whale ka main diet hai.': False,
    'Deep sea vent bacteria sunlight ke bina survive karte hain.': False,
    'Whale shark duniya ki sabse badi fish hai jo harmless plankton khati hai.': False,
    'Dolphin high frequency clicks se echolocation use karti hai.': False,
    'Narwhal ko ocean ka unicorn kaha jata hai unke long tusk ki wajah se.': False,
    'Sea otter shell todne ke liye stones use karte hain.': False,
    'Pelican samundar ke upar se dive karke fish pakadte hain.': False,
    'Albatross bina wings hillae ghanto tak fly kar sakte hain.': False,
    'Penguin underwater fast swim karte hain wings ki jagah flippers se.': False,
    'Giant squid deep ocean me rehta hai aur mythos ka part raha hai.': False,
    'Vampire squid oxygen-poor deep water me survive karta hai.': False,
    'Cone snail ka venom human ke liye fatal ho sakta hai.': False,
    'Parrotfish coral khakar sand produce karti hai beach par.': False,
    'Cleaner wrasse dusri fish ke parasites clean karti hai.': False,
    'Humpback whales complex songs sing karti hain.': False,
    'Ocean currents marine life migration me help karti hain.': False,
    'Marine conservation coral reefs aur ocean health ke liye zaroori hai.': False
}

# 6. factoryEngineers (50 items)
factoryEngineers = {
    'Factories me AI aur robots se production fast ho gaya hai.': True,
    'CNC machines metal cutting me 100% precision deti hain.': True,
    'Factory safety ke liye emergency shutdowns hote hain.': True,
    'Automobile lines par cars kuch ghante me banti hain.': True,
    'Engineers energy save karne ke liye solar use karte hain.': True,
    'Industrial automation human error ko minimize karta hai.': False,
    'Robotic arms welding aur painting ke liye use hoti hain.': False,
    'Quality control sensors defective products detect karte hain.': False,
    'Lean manufacturing waste reduce karne par focus karti hai.': False,
    'Six Sigma methodology process improvement ke liye hoti hai.': False,
    'Preventive maintenance machines breakdown hone se bachati hai.': False,
    'CAD software se parts ki 3D modeling ki jaati hai.': False,
    'PLC (Programmable Logic Controller) factory machines control karta hai.': False,
    'Conveyor belts materials ek jagah se dusri jagah move karti hain.': False,
    'Supply chain management raw material timing manage karta hai.': False,
    'Industrial IoT (IIoT) real-time data monitoring deta hai.': False,
    'Assembly line Henry Ford ne popular ki thi.': False,
    'PPE (Personal Protective Equipment) workers ki safety ke liye zaroori hai.': False,
    'Ergonomics workers ki physical strain ko kam karta hai.': False,
    'Material handling equipment heavy loads lift karta hai.': False,
    'Hydraulic systems high pressure force generate karte hain.': False,
    'Pneumatic systems compressed air par kaam karte hain.': False,
    'Electrical panels factory ki power supply manage karte hain.': False,
    'Boilers steam generation ke liye factories me hote hain.': False,
    'Cooling towers excess heat remove karte hain machines se.': False,
    'Welding techniques me MIG, TIG aur Arc welding aati hain.': False,
    'Metal casting molten metal ko molds me pour karke shape deti hai.': False,
    'Forging metal ko hammer karke strong banati hai.': False,
    'Machining process me turning, milling aur drilling hoti hain.': False,
    'Additive manufacturing ya 3D printing layer by layer parts banati hai.': False,
    'Industrial robots repetitive tasks bina thake karte hain.': False,
    'Sensors temperature, pressure aur vibration measure karte hain.': False,
    'Data analytics factory efficiency ko optimize karti hai.': False,
    'Green manufacturing eco-friendly processes adopt karti hai.': False,
    'Zero waste factories environmental impact minimize karti hain.': False,
    'Packaging machines products ko fast pack karti hain.': False,
    'Warehouse automation inventory management easy banata hai.': False,
    'Forklifts pallets transport karne ke liye use hote hain.': False,
    'Cranes heavy machinery lift karne me help karti hain.': False,
    'Industrial engineering process optimization par work karti hai.': False,
    'Root cause analysis machine failure ke real reason find karta hai.': False,
    'Standard Operating Procedures (SOPs) quality maintain rakhti hain.': False,
    'Shift scheduling 24/7 production ensure karti hai.': False,
    'Apprentice programs young engineers ko train karte hain.': False,
    'Research and Development naye products design karti hai.': False,
    'Prototyping mass production se pehle testing ke liye hoti hai.': False,
    'Tolerance levels engineering drawings me specify kiye jaate hain.': False,
    'Metrology precision measurement ke liye use hoti hai.': False,
    'Smart factories Industry 4.0 standards follow karti hain.': False,
    'Digital twins virtual factory models real-time simulation dete hain.': False
}

# 7. CivilizationAncientPeople (50 items)
CivilizationAncientPeople = {
    'Indus Valley me advanced underground drainage tha.': True,
    'Egyptians ne bina modern machines ke pyramids banaye.': True,
    'Maya civilization ka calendar bilkul sateek tha.': True,
    'Mesopotamia me sabse pehli written script bani thi.': True,
    'Purane log cave me hunting ki painting banate the.': True,
    'Sumerians ne wheel (pahiya) invent kiya tha.': False,
    'Chinese civilization ne paper aur gunpowder banaye the.': False,
    'Greek civilization me democracy aur philosophy start hui thi.': False,
    'Roman empire apne roads aur aqueducts ke liye famous tha.': False,
    'Inca civilization ne Andes mountains me roads banaye the.': False,
    'Aztec civilization floating gardens (chinampas) use karti thi.': False,
    'Harappan seals par mysterious script mili hai jo padhi nahi gayi.': False,
    'Stonehenge monument ancient astronomy se juda hai.': False,
    'Gobekli Tepe duniya ka sabse purana temple complex mana jata hai.': False,
    'Babylon ki hanging gardens ancient wonders me aati hain.': False,
    'Mummification process ancient Egypt me dead bodies preserve karne ke liye thi.': False,
    'Hieroglyphics Egyptian pictographic writing system hai.': False,
    'Cuneiform Mesopotamia ki wedge-shaped writing thi.': False,
    'Oracle bones ancient China me future predict karne ke liye use hote the.': False,
    'Gladiators Roman colosseum me fight karte the.': False,
    'Spartan children ki harsh training hoti thi warrior banane ke liye.': False,
    'Athens art, science aur literature ka center tha.': False,
    'Persian empire postal system aur roads ke liye jana jata tha.': False,
    'Phoenicians ne sabse pehla alphabetic script banaya tha.': False,
    'Minoan civilization Crete island par flourish hui thi.': False,
    'Mycenaean civilization early Greek history ka part hai.': False,
    'Olmec civilization giant stone heads ke liye famous hai.': False,
    'Easter Island ke moai statues mysterious hain.': False,
    'Anasazi cliff dwellings North America me milti hain.': False,
    'Viking warriors seafaring aur exploration ke liye jaane jaate the.': False,
    'Celtic tribes Europe me druid culture follow karti thin.': False,
    'Aboriginal people Australia ki oldest continuous culture hain.': False,
    'Polynesian navigators stars dekh kar ocean cross karte the.': False,
    'Silk Road ancient trade route tha jo East aur West ko connect karta tha.': False,
    'Bronze Age me metal tools aur weapons banna shuru hue the.': False,
    'Iron Age ke aane se farming aur warfare advance ho gayi.': False,
    'Megrilithic tombs ancient burial sites kehte hain.': False,
    'Terracotta Army China me emperor ke sath bury ki gayi thi.': False,
    'Machu Picchu Inca city high mountains par sthit hai.': False,
    'Chichen Itza Maya pyramid equinox ke din shadow snake banata hai.': False,
    'Alexandria library ancient world ka knowledge hub tha.': False,
    'Colossus of Rhodes ancient world ka giant statue tha.': False,
    'Pharaohs Egypt ke divine kings maane jaate the.': False,
    'Ziggurats Mesopotamia ke step pyramids the.': False,
    'Nomadic tribes agriculture se pehle hunter-gatherer life jeeti thin.': False,
    'Neolithic revolution ke baad farming shuru hui thi.': False,
    'Fire discovery early humans ke liye game changer thi.': False,
    'Cave paintings prehistoric humans ki lifestyle dikhati hain.': False,
    'Ancient mathematics geometry aur astronomy par based thi.': False,
    'Historical artifacts carbon dating se age measure ki jaati hai.': False
}

# 8. FlyVehicles (50 items)
FlyVehicles = {
    'Future ki flying taxis eVTOL tech par base hain.': True,
    'Supersonic jets London se New York safar aadha karenge.': True,
    'Delivery drones GPS tracking se packages bhejte hain.': False,
    'Lightweight materials se planes ka wajan kam hota hai.': False,
    'Mars ke liye special flying drones design huye hain.': False,
    'Wright brothers ne 1903 me pehli flight fly ki thi.': False,
    'Commercial airplanes jet engines par operate karte hain.': False,
    'Helicopters vertical takeoff aur landing kar sakte hain.': False,
    'Concorde supersonic passenger jet history ka iconic plane tha.': False,
    'Fighter jets mach speed se zyada fast ud sakte hain.': False,
    'Stealth technology planes ko radar se hide karti hai.': False,
    'Autopilot systems modern flights ko safely navigate karte hain.': False,
    'Air traffic control sky me collision avoid karta hai.': False,
    'Hot air balloons hot air ki buoyancy par fly karte hain.': False,
    'Gliders bina engine ke air currents par glide karte hain.': False,
    'Seaplanes pani par land aur takeoff kar sakte hain.': False,
    'Cargo planes heavy goods transport karne ke liye hote hain.': False,
    'Refueling aircraft mid-air me doosre plane me fuel transfer karte hain.': False,
    'Unmanned Aerial Vehicles (UAVs) military aur civilian use me hain.': False,
    'Spaceplanes atmosphere aur space dono me fly kar sakte hain.': False,
    'Electric aircrafts zero emission aviation goal par work kar rahe hain.': False,
    'Hydrogen powered planes future aviation ki direction hain.': False,
    'Jet streams high altitude strong winds hoti hain jo flight speed affect karti hain.': False,
    'Black box flight recorder crash investigation ke liye hota hai.': False,
    'Radar altimeter ground se height measure karta hai.': False,
    'Cockpit me dual controls pilot aur co-pilot ke paas hote hain.': False,
    'Turbulence air pocket ya wind shear ki wajah se hoti hai.': False,
    'Lift, weight, thrust aur drag flight ke 4 main forces hain.': False,
    'Aerodynamics wings ki shape par air pressure create karti hai.': False,
    'Fuselage airplane ka main body structure hota hai.': False,
    'Landing gear wheels aur brakes ko support karta hai.': False,
    'Flaps takeoff aur landing ke waqt lift increase karte hain.': False,
    'Rudder plane ko left ya right turn karne me help karta hai.': False,
    'Elevators pitch control ke liye horizontal tails par hote hain.': False,
    'Ailerons roll control ke liye wings par hote hain.': False,
    'Helicopter rotor blades lift aur thrust dono generate karte hain.': False,
    'Tiltrotor aircraft plane aur helicopter dono ki tarah fly karte hain.': False,
    'Quadcopters 4 rotors se balance aur stability paate hain.': False,
    'Agricultural drones fields me pesticide spray karne ke liye use hote hain.': False,
    'Search and rescue drones disaster sites par search me help karte hain.': False,
    'Parachutes emergency escape ke liye use hote hain.': False,
    'Ejection seats fighter jets me pilot ki jaan bachati hain.': False,
    'Flight simulators pilots ki training ke liye use hote hain.': False,
    'Airport runways lights aur markings se guide kiye jaate hain.': False,
    'Jet fuel kerosene based special liquid hota hai.': False,
    'Sonic boom jab plane speed of sound cross karta hai tab create hota hai.': False,
    'Scramjet engines hypersonic speeds achieve karne ke liye hote hain.': False,
    'Airships ya zeppelins helium gas se float karte hain.': False,
    'Solar powered planes continuous flight records banate hain.': False,
    'Urban air mobility future cities me traffic solve karne ka plan hai.': False
}

# 9. GandhiMarch (50 items)
GandhiMarch = {
    'Gandhi ji ne 1930 me Dandi march kiya tha.': True,
    'Dandi March se freedom struggle me log jude.': True,
    'Is march ne British economy ko bada jhatka diya.': False,
    'Sabarmati Ashram se ahimsa ki yatra shuru hui.': False,
    'Is movement ne Indian independence ko taqat di.': False,
    'Salt Satyagraha british salt tax ke against tha.': False,
    'Dandi march 385 kilometers long foot march thi.': False,
    '78 followers ne Gandhi ji ke sath march start kiya tha.': False,
    '24 days tak ye yatra chali thi.': False, # Wait, keep regular syntax:
    '24 days tak ye yatra chali thi.': False,
    '6 April 1930 ko namak todkar kanoon todha gaya tha.': False,
    'Civil Disobedience Movement ki shuruwat isse hui thi.': False,
    'International media ne is event ko widely cover kiya tha.': False,
    'Sarojini Naidu bhi is movement ki prominent leader thin.': False,
    'Dharasana salt works protest bhi iske baad hua tha.': False,
    'Khadi cloth ko promote karna Swadeshi movement ka part tha.': False,
    'Ahimsa aur Satyagraha Gandhi ji ke main weapons the.': False,
    'Champaran satyagrah indigo farmers ke liye tha.': False,
    'Kheda satyagrah tax relief ke liye organize hua tha.': False,
    'Non-Cooperation movement 1920 me launch hua tha.': False,
    'Quit India movement 1942 me Do or Die slogan ke sath aaya tha.': False,
    'Round Table Conferences me Gandhi ji ne participate kiya tha.': False,
    'Gandhi-Irwin Pact political prisoners release ke liye tha.': False,
    'Poona Pact depressed classes representation ke liye sign hua tha.': False,
    'Young India aur Harijan newspapers Gandhi ji run karte the.': False,
    'Autobiography My Experiments with Truth famous book hai.': False,
    'Aga Khan Palace me Gandhi ji imprisoned rahe the.': False,
    'Birla House Delhi me unka assassination hua tha.': False,
    '2 October Gandhi Jayanti International Non-Violence day ban gaya.': False,
    'South Africa me bhi Gandhi ji ne racial discrimination ke against fight ki thi.': False,
    'Natal Indian Congress founding me unka role tha.': False,
    'Tolstoy Farm South Africa me establish ki gayi thi.': False,
    'Phoenix Settlement bhi wahi banayi gayi thi.': False,
    'Mahatma title unhe Rabindranath Tagore ne diya tha.': False,
    'Father of the Nation unhe Netaji Subhas Chandra Bose ne kaha tha.': False,
    'Chauri Chaura incident ke baad non-cooperation roka gaya tha.': False,
    'Rowlatt Act ke against protest nationwide hua tha.': False,
    'Jallianwala Bagh massacre ne freedom struggle ko intense kar diya tha.': False,
    'Khilafat movement me Muslim leaders ke sath alliance hua tha.': False,
    'Swaraj self-rule ka goal Gandhi ji ne set kiya tha.': False,
    'Village self-reliance aur gram swaraj par unka focus tha.': False,
    'Untouchability eradication ke liye unne kafi kaam kiya.': False,
    'Hindu-Muslim unity ke liye unhone fasts rakhe the.': False,
    'Basic education (Nai Talim) concept unhone introduce kiya tha.': False,
    'Charkha self-reliance aur simplicity ka symbol ban gaya.': False,
    'Prarthana meetings me bhajan gae jaate the.': False,
    'Vaikom satyagrah temple entry rights ke liye tha.': False,
    'Bardoli satyagrah ko Vallabhbhai Patel ne lead kiya tha.': False,
    'Cabinet Mission plan independence se pehle discuss hua tha.': False,
    'Mountbatten Plan partition aur transfer of power ke liye tha.': False,
    'Indian Constitution drafting me Gandhian ideals include hue the.': False
}

# 10. PoliceSearching (50 items)
PoliceSearching = {
    'Forensic science me DNA profiling bada hathiyar hai.': True,
    'CCTV footage se criminal tezi se pakde jaate hain.': True,
    'Trained police dogs ki sunghne ki shakti tez hoti hai.': False,
    'Cyber cells online frauds ko track karte hain.': False,
    'Night patrolling se shehar me security rehti hai.': False,
    'Fingerprint analysis unique identity match karta hai.': False,
    'Ballistic testing se gun aur bullet match ki jaati hai.': False,
    'Lie detector polygraph tests suspect interrogation me use hote hain.': False,
    'CSI teams crime scene se evidence collect karti hain.': False,
    'Missing person search operations me drones use hote hain.': False,
    'Highway checkposts pe vehicles ki checking hoti hai.': False,
    'Interpol international police cooperation network hai.': False,
    'Undercover operations me police secret agent bhejti hai.': False,
    'Raid actions me illegal substances ya criminals pakde jaate hain.': False,
    'APIS system automated fingerprint identification karta hai.': False,
    'CCIS database criminal records maintain rakhta hai.': False,
    'Emergency helpline numbers quick response ke liye hote hain.': False,
    'SWAT teams high-risk hostage situations handle karti hain.': False,
    'Bomb disposal squads explosives neutralise karte hain.': False,
    'Traffic police road safety aur rules enforce karti hai.': False,
    'Speed cameras overspeeding vehicles detect karte hain.': False,
    'Breathalyzer tests drunk driving check karte hain.': False,
    'FIR (First Information Report) legal investigation start karti hai.': False,
    'Warrants court se arrest ya search ke liye issue hote hain.': False,
    'Interrogation rooms me suspect se questioning hoti hai.': False,
    'Witness protection programs important gawahon ki jaan bachate hain.': False,
    'Stalker aur cyberbullying tracking ke liye digital forensics hoti hai.': False,
    'Money laundering trails financial crimes expose karti hain.': False,
    'Counterfeit currency detection machines fake notes pakadti hain.': False,
    'Anti-narcotics cells drugs smuggling rokti hain.': False,
    'Human trafficking rescue operations me police raid karti hai.': False,
    'Juvenile justice boards minor offenders ke liye hote hain.': False,
    'Prison security systems inmates ko monitor karte hain.': False,
    'Police academies recruits ko physical aur legal training deti hain.': False,
    'Community policing public trust build karne me help karti hai.': False,
    'PCR vans emergency me sabse pehle spot par pahunchti hain.': False,
    'Blue corner notice international enquiries ke liye hota hai.': False,
    'Red corner notice wanted criminals arrest karne ke liye hota hai.': False,
    'Autopsy reports death cause determine karti hain.': False,
    'Toxicology tests poison ya drugs detect karte hain.': False,
    'Blood spatter analysis crime scene reconstruction me help karta hai.': False,
    'Footprint casting shoe tracks match karne ke liye hoti hai.': False,
    'Composite sketches eyewitness description se banaye jaate hain.': False,
    'Stolen vehicle tracking GPS systems se hoti hai.': False,
    'Phone tap legal authorization ke sath communication monitor karta hai.': False,
    'Sting operations journalism aur police investigation me use hote hain.': False,
    'Border security forces illegal infiltration rokti hain.': False,
    'Riots control gear me tear gas aur shields use hoti hain.': False,
    'VIP security details prominent leaders ki protection karti hain.': False,
    'Crime prevention campaigns public awareness badhati hain.': False
}

# 11. RoketSatellite (50 items)
RoketSatellite = {
    'SpaceX ke rockets wapas zameen par safe land hote hain.': False,
    'Communication satellites internet signals deti hain.': False,
    'ISRO ke launch vehicles cost-effective hote hain.': False,
    'Space debris active satellites ke liye khatra hai.': False,
    'Weather satellites toofan ki jankari pehle deti hain.': False,
    'PSLV ISRO ka workhorse launch vehicle hai.': False,
    'GSLV heavy payloads geostationary orbit me bhejta hai.': False,
    'Reusable rockets space travel ka cost drastically kam karte hain.': False,
    'Low Earth Orbit (LEO) me Starlink jese constellations hote hain.': False,
    'Geostationary satellites earth ke sath synchronous rotate karti hain.': False,
    'GPS satellites navigation aur timing signals provide karti hain.': False,
    'Hubble Space Telescope deep space images capture karta hai.': False,
    'James Webb Space Telescope infrared astronomy me advance hai.': False,
    'International Space Station (ISS) space me orbiting lab hai.': False,
    'Mars rovers red planet ki surface explore karte hain.': False,
    'Lunar orbiters moon mapping aur water ice search karte hain.': False,
    'Solar panels satellites ko electricity provide karte hain.': False,
    'Rocket propulsion Newton ke third law par work karta hai.': False,
    'Liquid propellant rockets me fuel aur oxidizer tanks hote hain.': False,
    'Solid rocket boosters initial thrust provide karte hain.': False,
    'Escape velocity earth ki gravity overcome karne ke liye zaroori hai.': False,
    'Payload wo weight hota hai jo rocket space me carry karta hai.': False,
    'Countdown sequence launch se pehle sare systems check karta hai.': False,
    'Mission control center rocket launch ko monitor karta hai.': False,
    'Telemetry data real-time rocket health send karta hai ground par.': False,
    'Fairing rocket ke top par satellite ko aerodynamic protection deti hai.': False,
    'Stages separation ke baad empty tanks drop kar diye jaate hain.': False,
    'Orbital insertion satellite ko target orbit me place karta hai.': False,
    'Space probes planets ke beyond solar system explore karte hain.': False,
    'Voyager 1 interstellar space me enter karne wala pehla craft hai.': False,
    'Chandrayaan mission India ka moon exploration project hai.': False,
    'Mangalyaan Mars orbit me successfully enter hua tha pehli baar me.': False,
    'Aditya-L1 sun study karne ke liye ISRO ka mission hai.': False,
    'Gaganyaan India ka human spaceflight mission hai.': False,
    'Space tourism future me civilians ko space le jayega.': False,
    'Asteroid mining future resources ke liye propose ki gayi hai.': False,
    'Space suits astronauts ko vacuum aur radiation se bachate hain.': False,
    'Microgravity environment me human body par effects hote hain.': False,
    'Satellite TV broadcast direct homes tak signals pahunchata hai.': False,
    'Remote sensing satellites agriculture aur disaster mapping karte hain.': False,
    'Military reconnaissance satellites intelligence gathering karti hain.': False,
    'Space weather solar flares aur geomagnetic storms track karta hai.': False,
    'Kessler syndrome space debris cascade collision ko kehte hain.': False,
    'Debris removal missions active clean-up par work kar rahe hain.': False,
    'Ion engines efficient electric propulsion use karte hain long missions me.': False,
    'Centrifugal force orbit me satellites ko balance rakhti hai.': False,
    'Apogee orbit ka farthest point hota hai.': False,
    'Perigee orbit ka closest point hota hai.': False,
    'Space launch complexes coastal areas me kyu banaye jaate hain safety ke liye.': False,
    'Astrophysics universe ke origin aur laws explain karti hai.': False
}

# 12. Machines (50 items)
Machines = {
    'Industrial machines kharab hone ki warning de deti hain.': True,
    'Quantum computers complex calculations fast solve karte hain.': True,
    '3D printing se metal parts ghar print hote hain.': True,
    'Excavators big construction projects me use hote hain.': True,
    'Automated weaving looms tezi se kapde banate hain.': True,
    'CNC mills computer program se metal shape karti hain.': True,
    'Lathe machine rotation se cylindrical parts banati hai.': True,
    'Injection molding plastic products mass produce karti hai.': False,
    'Robotic arms electronics assembly me precision deti hain.': False,
    'Conveyor systems material handling easy banate hain.': False,
    'Hydraulic presses heavy metal stamping ke liye hoti hain.': False,
    'Steam turbines power plants me electricity generate karte hain.': False,
    'Internal combustion engines fossil fuels par chalte hain.': False,
    'Electric motors electrical energy ko mechanical energy me badalti hain.': False,
    'Generators mechanical energy ko electricity me convert karte hain.': False,
    'Transformers voltage levels step up ya down karte hain.': False,
    'Compressors air pressure increase karte hain pneumatic tools ke liye.': False,
    'Pumps liquids transport karne ke liye pipelines me use hote hain.': False,
    'Heat exchangers thermal energy transfer karte hain systems ke beech.': False,
    'Industrial boilers high pressure steam produce karte hain.': False,
    'Centrifuges high speed rotation se liquids separate karte hain.': False,
    'Packaging machines food aur consumer goods pack karti hain.': False,
    'Sorting machines barcodes aur sensors se items categorize karti hain.': False,
    'Laser cutters high precision se materials cut karte hain.': False,
    'Plasma cutters metal sheets par fast cutting ke liye hote hain.': False,
    'Industrial robots hazardous environment me work karte hain.': False,
    'AGVs (Automated Guided Vehicles) warehouse me items move karte hain.': False,
    'Forklifts pallets lift aur transport karne ke liye hote hain.': False,
    'Cranes skyscrapers construction me heavy materials lift karti hain.': False,
    'Bulldozers land clearing aur soil pushing ke liye use hote hain.': False,
    'Road rollers asphalt surface compact karte hain.': False,
    'Concrete mixers cement, sand aur water mix karte hain.': False,
    'Tractors agricultural fields me farming operations karte hain.': False,
    'Harvesters crops cutting aur threshing ek sath karte hain.': False,
    'Printing presses newspapers aur books mass print karti hain.': False,
    'ATM machines cash dispensing ke liye automated systems hain.': False,
    'Vending machines coins ya cards se items deliver karti hain.': False,
    'Washing machines clothes cleaning automate karti hain.': False,
    'Refrigerators cooling technology se food fresh rakhte hain.': False,
    'Air conditioners temperature aur humidity control karte hain.': False,
    'Microwave ovens electromagnetic waves se food heat karte hain.': False,
    'Dishwashers utensils automatic water spray se clean karte hain.': False,
    'Vacuum cleaners suction force se dust clean karte hain.': False,
    'Sewing machines fabric stitching fast karti hain.': False,
    'X-ray machines medical imaging ke liye use hoti hain.': False,
    'MRI scanners magnetic fields se internal organs scan karte hain.': False,
    'CT scan machines cross-sectional images generate karti hain.': False,
    'Dialysis machines kidney failure patients ka blood filter karti hain.': False,
    'Ventilators patient ko breathing support provide karte hain ICU me.': False,
    'Prosthetic limbs mechanical joints se mobility wapas laate hain.': False
}

# 13. ScientistExperiments (50 items)
ScientistExperiments = {
    'CERN ka Collider universe ke raaz kholta hai.': True,
    'CRISPR gene editing se DNA me badlav hota hai.': False,
    'Quantum physics me particles ajeeb state me hote hain.': False,
    'Nanotechnology me atomic scale par work hota hai.': False,
    'Labs me controlled reactions se medicines banti hain.': False,
    'Double-slit experiment light ka wave-particle duality show karta hai.': False,
    'Schrödinger cat thought experiment quantum superposition explain karta hai.': False,
    'Pavlov dog experiment classical conditioning prove karta hai.': False,
    'Milgram experiment obedience to authority test karta hai.': False,
    'Stanford prison experiment human behavior study karta hai.': False,
    'Galileo gravity experiment Pisa tower se balls drop karke kiya tha.': False,
    'Newton prism experiment se white light spectrum discover kiya tha.': False,
    'Mendel pea plant experiment genetics ke laws establish karta hai.': False,
    'Pasteur rabies vaccine aur pasteurization process invent ki thi.': False,
    'Fleming penicillin antibiotic serendipity se discover ki thi.': False,
    'Curie radiation research me radium aur polonium find kiye the.': False,
    'Einstein relativity theory space-time fabric explain karti hai.': False,
    'Tesla alternating current electrical system develop kiya tha.': False,
    'Edison light bulb experiments me hazaro attempts kiye the.': False,
    'Darwin evolution theory Galapagos islands par study karke di thi.': False,
    'Goodall chimpanzee research animal behavior par groundbreaking thi.': False,
    'Hawking radiation black holes se related theory thi.': False,
    'Turing test artificial intelligence human-like intelligence measure karta hai.': False,
    'Meselson-Stahl experiment DNA replication semi-conservative prove karta hai.': False,
    'Hershey-Chase experiment DNA ko genetic material confirm karta hai.': False,
    'Franklin X-ray crystallography se DNA structure discover karne me help ki.': False,
    'Millikan oil drop experiment electron charge measure karta hai.': False,
    'Rutherford gold foil experiment atom ke nucleus ko discover karta hai.': False,
    'J.J. Thomson cathode ray tube se electron find kiya tha.': False,
    'Bohr atomic model quantum orbits explain karta hai.': False,
    'Periodic table Mendeleev ne elements arrange karke banai thi.': False,
    'Haber-Bosch process synthetic ammonia fertilizer banati hai.': False,
    'Polymers aur plastics ki discovery modern material science badal di.': False,
    'Superconductivity experiments extremely low temperatures par hote hain.': False,
    'Nuclear fission experiments atomic energy discover karte hain.': False,
    'Particle accelerators subatomic particles ko high speed par collide karate hain.': False,
    'Gravitational waves LIGO detectors se record ki gayi hain.': False,
    'Exoplanet discovery telescopes se dusre solar systems me hoti hai.': False,
    'Stem cell research regenerative medicine me new hope deti hai.': False,
    'Cloning experiments me Dolly the sheep sabse pehle successful thi.': False,
    'MRI machine development ke liye Nobel prize mila tha.': False,
    'PCR test DNA amplification ke liye molecular biology me use hota hai.': False,
    'Photosynthesis experiments plants me light energy conversion show karte hain.': False,
    'Enzyme kinetics biochemical reactions speed study karti hai.': False,
    'Electrochemistry batteries aur fuel cells research me use hoti hai.': False,
    'Astrobiology space me life possibilities explore karti hai.': False,
    'Cryogenics ultra-low temperature properties test karti hai.': False,
    'Plasma physics fusion energy research ke liye important hai.': False,
    'Biotechnology genetically modified organisms develop karti hai.': False,
    'Scientific method observation, hypothesis, experiment aur conclusion par based hai.': False
}
